import type { LexiconTerm } from '@/types';

/**
 * Static lexicon data - the local knowledge base
 * This is the primary data source before external API calls
 *
 * Categories:
 * - core: Fundamental concepts everyone should know
 * - architecture: System design and components
 * - protocols: Standards and communication patterns
 * - orchestration: Multi-agent coordination
 * - safety: Security, alignment, and governance
 * - techniques: Prompting and reasoning methods
 * - evolution: Learning and adaptation
 * - prompting: Prompt engineering techniques
 * - frameworks: Agent frameworks and libraries
 * - evaluation: Testing, benchmarking, and metrics
 * - enterprise: Production deployment concepts
 * - ethics: AI ethics and alignment
 * - ml-fundamentals: Machine learning basics
 * - nlp: Natural language processing
 * - infrastructure: Compute and deployment
 */
export const staticLexicon: LexiconTerm[] = [
  // ============================================
  // CORE CONCEPTS
  // ============================================
  {
    term: 'Agent',
    definition: 'An autonomous AI system capable of perceiving its environment, making decisions, and taking actions to achieve specified goals. Modern AI agents typically combine large language models with tool access and memory systems.',
    level: 'novice',
    category: 'core',
    tags: ['fundamentals', 'autonomy'],
  },
  {
    term: 'Agentic AI',
    definition: 'AI systems that exhibit agency - the capacity to act autonomously, make decisions, and pursue goals over extended time horizons. Distinguished from traditional AI by persistent state, tool use, and multi-step reasoning.',
    level: 'novice',
    category: 'core',
    tags: ['fundamentals', 'autonomy'],
  },
  {
    term: 'LLM',
    definition: 'Large Language Model - A neural network trained on vast text corpora, capable of understanding and generating human language. Forms the cognitive core of most modern AI agents. Examples include GPT-4, Claude, Gemini, and Llama.',
    level: 'novice',
    category: 'core',
    tags: ['models', 'fundamentals'],
  },
  {
    term: 'Foundation Model',
    definition: 'A large AI model trained on broad data that can be adapted to many downstream tasks. Foundation models like GPT-4 or Claude serve as the base for specialized agents and applications.',
    level: 'novice',
    category: 'core',
    tags: ['models', 'fundamentals'],
  },
  {
    term: 'Inference',
    definition: 'The process of running a trained model to generate predictions or outputs. When you chat with an AI, each response is an inference. Inference costs (compute, latency) are a key consideration in agent design.',
    level: 'novice',
    category: 'core',
    tags: ['fundamentals', 'compute'],
  },
  {
    term: 'Context Window',
    definition: 'The maximum amount of text (measured in tokens) a model can process in a single inference. Larger context windows enable longer conversations and more complex reasoning. Modern models range from 8K to 2M+ tokens.',
    level: 'novice',
    category: 'core',
    tags: ['fundamentals', 'limitations'],
  },
  {
    term: 'Token',
    definition: 'The basic unit of text processing for LLMs. A token is typically 3-4 characters or roughly 0.75 words in English. Models have limits on input and output tokens, and pricing is often per-token.',
    level: 'novice',
    category: 'core',
    tags: ['fundamentals', 'nlp'],
  },
  {
    term: 'Prompt',
    definition: 'The input text given to an LLM to elicit a response. Prompts can include instructions, examples, context, and the actual query. The quality of the prompt significantly affects output quality.',
    level: 'novice',
    category: 'core',
    tags: ['fundamentals', 'prompting'],
  },
  {
    term: 'Completion',
    definition: 'The output text generated by an LLM in response to a prompt. Also called a response or generation. The model predicts the most likely tokens to follow the input.',
    level: 'novice',
    category: 'core',
    tags: ['fundamentals', 'generation'],
  },
  {
    term: 'Hallucination',
    definition: 'When an LLM generates plausible-sounding but factually incorrect or nonsensical content. A major challenge in AI deployment, mitigated through grounding, retrieval, and verification.',
    level: 'novice',
    category: 'core',
    tags: ['limitations', 'safety'],
  },
  {
    term: 'Grounding',
    definition: 'Connecting AI outputs to verifiable sources of truth, such as databases, documents, or real-time data. Grounding reduces hallucinations and increases reliability.',
    level: 'intermediate',
    category: 'core',
    tags: ['reliability', 'rag'],
  },
  {
    term: 'Multimodal',
    definition: 'AI systems capable of processing multiple types of input (text, images, audio, video) and potentially generating multiple output types. GPT-4V, Gemini, and Claude 3 are multimodal models.',
    level: 'novice',
    category: 'core',
    tags: ['models', 'capabilities'],
  },
  {
    term: 'Embedding',
    definition: 'A dense vector representation of text, images, or other data that captures semantic meaning. Similar items have similar embeddings. Used for semantic search, clustering, and retrieval.',
    level: 'intermediate',
    category: 'core',
    tags: ['vectors', 'retrieval'],
  },
  {
    term: 'Vector Database',
    definition: 'A database optimized for storing and querying high-dimensional vectors (embeddings). Enables fast similarity search for RAG systems. Examples: Pinecone, Weaviate, Chroma, Milvus.',
    level: 'intermediate',
    category: 'core',
    tags: ['infrastructure', 'retrieval'],
  },
  {
    term: 'Latency',
    definition: 'The time delay between sending a request to an AI system and receiving a response. Critical for user experience and real-time applications. Measured in milliseconds or seconds.',
    level: 'novice',
    category: 'core',
    tags: ['performance', 'infrastructure'],
  },
  {
    term: 'Throughput',
    definition: 'The number of requests or tokens an AI system can process per unit time. Important for scaling agents to handle multiple concurrent users or tasks.',
    level: 'intermediate',
    category: 'core',
    tags: ['performance', 'infrastructure'],
  },

  // ============================================
  // ARCHITECTURE
  // ============================================
  {
    term: 'ReAct',
    definition: 'Reasoning and Acting pattern - An agent architecture that interleaves reasoning traces with action execution. The agent thinks about what to do, takes an action, observes the result, and reasons about next steps.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['patterns', 'reasoning'],
  },
  {
    term: 'Memory System',
    definition: 'Components that enable agents to store and retrieve information across time. Includes working memory (current context), episodic memory (past experiences), and semantic memory (general knowledge).',
    level: 'intermediate',
    category: 'architecture',
    tags: ['memory', 'persistence'],
  },
  {
    term: 'Planning Engine',
    definition: 'A component that generates sequences of actions to achieve goals. May use classical planning algorithms, LLM-based planning, or hybrid approaches combining both.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['planning', 'goals'],
  },
  {
    term: 'Tool Use',
    definition: 'An agent\'s ability to invoke external functions, APIs, or systems to accomplish tasks. Tools extend agent capabilities beyond pure language processing to real-world actions.',
    level: 'novice',
    category: 'architecture',
    tags: ['tools', 'capabilities'],
  },
  {
    term: 'Function Calling',
    definition: 'A capability where LLMs can output structured JSON to invoke predefined functions. The model decides when to call functions and with what parameters. Key enabler of tool use.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['tools', 'api'],
  },
  {
    term: 'RAG',
    definition: 'Retrieval-Augmented Generation - A pattern where relevant documents are retrieved from a knowledge base and included in the prompt to ground LLM responses in factual content.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['retrieval', 'grounding'],
  },
  {
    term: 'GraphRAG',
    definition: 'Retrieval-Augmented Generation using Knowledge Graphs. Combines graph-based knowledge representation with retrieval to understand entity relationships and provide more contextual responses.',
    level: 'expert',
    category: 'architecture',
    tags: ['retrieval', 'knowledge-graphs'],
  },
  {
    term: 'Agentic RAG',
    definition: 'An evolution of RAG where agents iteratively query, evaluate, and refine retrieved information. The agent can reformulate queries, filter results, and synthesize from multiple sources.',
    level: 'expert',
    category: 'architecture',
    tags: ['retrieval', 'agents'],
  },
  {
    term: 'Neuro-Symbolic AI',
    definition: 'Approaches combining neural networks with symbolic reasoning. Aims to get the best of both: neural flexibility and symbolic interpretability, formal guarantees.',
    level: 'expert',
    category: 'architecture',
    tags: ['hybrid', 'reasoning'],
  },
  {
    term: 'Cognitive Architecture',
    definition: 'A blueprint for organizing agent components including perception, memory, reasoning, planning, and action. Examples include ACT-R, SOAR, and modern LLM-based architectures.',
    level: 'expert',
    category: 'architecture',
    tags: ['design', 'theory'],
  },
  {
    term: 'Reflection',
    definition: 'An agent\'s ability to examine and critique its own outputs, reasoning, or behavior. Enables self-correction and iterative improvement within a task.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['reasoning', 'improvement'],
  },
  {
    term: 'Self-Correction',
    definition: 'The capability for an agent to identify errors in its own outputs and fix them without external intervention. Often implemented through reflection and verification loops.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['reliability', 'reasoning'],
  },
  {
    term: 'Scratchpad',
    definition: 'A working memory space where agents can write intermediate thoughts, calculations, or drafts during multi-step reasoning. Helps manage complex tasks.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['memory', 'reasoning'],
  },
  {
    term: 'State Machine',
    definition: 'A computational model where an agent transitions between defined states based on inputs and actions. Useful for structured workflows with clear decision points.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['control-flow', 'patterns'],
  },
  {
    term: 'Router',
    definition: 'A component that directs inputs to appropriate handlers, models, or sub-agents based on intent classification or other criteria. Essential for complex multi-capability systems.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['orchestration', 'patterns'],
  },
  {
    term: 'Guardrails',
    definition: 'Safety constraints implemented to prevent agents from taking harmful actions or generating inappropriate content. Can be rule-based, model-based, or hybrid.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['safety', 'constraints'],
  },
  {
    term: 'Sandbox',
    definition: 'An isolated execution environment where agent code or actions can run without affecting the broader system. Critical for safely executing untrusted or generated code.',
    level: 'intermediate',
    category: 'architecture',
    tags: ['safety', 'execution'],
  },

  // ============================================
  // PROTOCOLS & STANDARDS
  // ============================================
  {
    term: 'MCP',
    definition: 'Model Context Protocol - Anthropic\'s open protocol standardizing how AI assistants connect to external tools and data sources. Provides a universal interface for tool integration.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['standards', 'tools', 'anthropic'],
  },
  {
    term: 'A2A',
    definition: 'Agent-to-Agent Protocol - Google\'s open protocol enabling direct communication between autonomous AI agents. Covers discovery, capability advertisement, and task delegation.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['standards', 'communication', 'google'],
  },
  {
    term: 'DID',
    definition: 'Decentralized Identifier - A URI that resolves to a DID Document, providing verifiable, decentralized digital identity. Format: did:method:identifier. Essential for agent identity in trustless environments.',
    level: 'expert',
    category: 'protocols',
    tags: ['identity', 'decentralization'],
  },
  {
    term: 'Verifiable Credentials',
    definition: 'W3C standard for cryptographically-secure digital credentials. Enables agents to prove capabilities, certifications, or permissions without revealing unnecessary information.',
    level: 'expert',
    category: 'protocols',
    tags: ['identity', 'security'],
  },
  {
    term: 'OpenAPI',
    definition: 'A specification for describing REST APIs in a machine-readable format. LLMs can use OpenAPI specs to understand and call APIs. Foundation for many tool integrations.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['api', 'tools'],
  },
  {
    term: 'JSON Schema',
    definition: 'A vocabulary for annotating and validating JSON documents. Used to define the structure of function parameters, tool inputs, and agent outputs.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['validation', 'structure'],
  },
  {
    term: 'Semantic Kernel',
    definition: 'Microsoft\'s SDK for integrating LLMs into applications. Provides abstractions for prompts, memory, planners, and connectors. Supports multiple AI providers.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['sdk', 'microsoft'],
  },
  {
    term: 'BASIS',
    definition: 'Blockchain Agent Standard for Identity and Security - A comprehensive framework combining identity, trust scoring, capability management, and governance for autonomous agents. Developed by Vorion.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['standards', 'identity', 'vorion'],
  },
  {
    term: 'ATSF',
    definition: 'Agent Trust Scoring Framework - A multi-dimensional framework within BASIS for evaluating agent trustworthiness across performance, security, compliance, and behavioral metrics.',
    level: 'expert',
    category: 'protocols',
    tags: ['trust', 'vorion', 'framework'],
  },
  {
    term: 'OAuth 2.0',
    definition: 'Authorization framework enabling third-party applications to access resources on behalf of users. Agents use OAuth to access user data and services with appropriate permissions.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['security', 'authorization'],
  },
  {
    term: 'WebSocket',
    definition: 'Protocol providing full-duplex communication channels over a single TCP connection. Enables real-time, bidirectional communication between agents and servers.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['communication', 'real-time'],
  },
  {
    term: 'SSE',
    definition: 'Server-Sent Events - A standard for servers to push data to clients over HTTP. Used for streaming LLM responses token-by-token to provide real-time feedback.',
    level: 'intermediate',
    category: 'protocols',
    tags: ['streaming', 'communication'],
  },

  // ============================================
  // MULTI-AGENT ORCHESTRATION
  // ============================================
  {
    term: 'Swarm Intelligence',
    definition: 'Collective behavior emerging from decentralized agents following simple rules. No single point of failure. Agents coordinate through local interactions and environmental signals.',
    level: 'expert',
    category: 'orchestration',
    tags: ['multi-agent', 'decentralization'],
  },
  {
    term: 'Hierarchical Orchestration',
    definition: 'Multi-agent coordination where agents are organized in a tree structure with supervisor-worker relationships. Supervisors delegate tasks and aggregate results.',
    level: 'intermediate',
    category: 'orchestration',
    tags: ['multi-agent', 'coordination'],
  },
  {
    term: 'Multi-Agent Debate',
    definition: 'Orchestration pattern where multiple agents with different perspectives argue and critique each other\'s reasoning. Leads to more robust conclusions through adversarial collaboration.',
    level: 'expert',
    category: 'orchestration',
    tags: ['multi-agent', 'reasoning'],
  },
  {
    term: 'Agent Handoff',
    definition: 'The transfer of control and context from one agent to another during task execution. Requires careful state management to maintain conversation coherence.',
    level: 'intermediate',
    category: 'orchestration',
    tags: ['multi-agent', 'coordination'],
  },
  {
    term: 'Consensus Mechanism',
    definition: 'A process by which multiple agents reach agreement on a decision or state. Can involve voting, proof-of-work, or other coordination protocols.',
    level: 'expert',
    category: 'orchestration',
    tags: ['multi-agent', 'decentralization'],
  },
  {
    term: 'Task Decomposition',
    definition: 'Breaking down complex tasks into smaller, manageable subtasks that can be executed independently or in sequence. Fundamental to multi-agent systems.',
    level: 'intermediate',
    category: 'orchestration',
    tags: ['planning', 'multi-agent'],
  },
  {
    term: 'Crew',
    definition: 'A coordinated group of specialized agents working together on complex tasks. Each crew member has a specific role, expertise, and set of tools.',
    level: 'intermediate',
    category: 'orchestration',
    tags: ['multi-agent', 'crewai'],
  },
  {
    term: 'Supervisor Agent',
    definition: 'An agent that coordinates other agents, delegating tasks and synthesizing results. Acts as a manager in hierarchical multi-agent systems.',
    level: 'intermediate',
    category: 'orchestration',
    tags: ['multi-agent', 'coordination'],
  },
  {
    term: 'Worker Agent',
    definition: 'A specialized agent that performs specific tasks under the direction of a supervisor or orchestrator. Focuses on narrow capabilities with deep expertise.',
    level: 'intermediate',
    category: 'orchestration',
    tags: ['multi-agent', 'specialization'],
  },
  {
    term: 'Agent Mesh',
    definition: 'A network topology where agents can communicate peer-to-peer without centralized coordination. Enables resilient, scalable multi-agent systems.',
    level: 'expert',
    category: 'orchestration',
    tags: ['multi-agent', 'architecture'],
  },
  {
    term: 'Blackboard System',
    definition: 'A multi-agent architecture where agents communicate through a shared knowledge store (blackboard). Agents read and write to the blackboard to coordinate.',
    level: 'expert',
    category: 'orchestration',
    tags: ['multi-agent', 'patterns'],
  },

  // ============================================
  // SAFETY & GOVERNANCE
  // ============================================
  {
    term: 'Trust Score',
    definition: 'A quantitative measure of an agent\'s trustworthiness, typically multi-dimensional. Encompasses performance history, security posture, compliance record, and behavioral consistency.',
    level: 'intermediate',
    category: 'safety',
    tags: ['trust', 'governance'],
  },
  {
    term: 'Capability Gating',
    definition: 'The practice of restricting agent capabilities based on trust level, context, and authorization. High-risk actions require higher trust thresholds or human approval.',
    level: 'intermediate',
    category: 'safety',
    tags: ['safety', 'access-control'],
  },
  {
    term: 'Human-in-the-Loop',
    definition: 'System design where humans review, approve, or correct AI decisions at certain points. Balances autonomy with oversight for safety-critical operations.',
    level: 'novice',
    category: 'safety',
    tags: ['safety', 'oversight'],
  },
  {
    term: 'Audit Trail',
    definition: 'A chronological record of agent actions, decisions, and their justifications. Enables accountability, debugging, and forensic analysis of agent behavior.',
    level: 'intermediate',
    category: 'safety',
    tags: ['accountability', 'logging'],
  },
  {
    term: 'Red Teaming',
    definition: 'Adversarial testing where humans or other AI systems attempt to find vulnerabilities, elicit harmful outputs, or bypass safety measures in AI systems.',
    level: 'intermediate',
    category: 'safety',
    tags: ['testing', 'security'],
  },
  {
    term: 'Jailbreaking',
    definition: 'Attempts to bypass an AI model\'s safety guidelines through clever prompting. A major security concern that motivates robust safety training and guardrails.',
    level: 'intermediate',
    category: 'safety',
    tags: ['security', 'attacks'],
  },
  {
    term: 'Prompt Injection',
    definition: 'An attack where malicious instructions are hidden in user input or retrieved content to manipulate agent behavior. Critical vulnerability in LLM applications.',
    level: 'intermediate',
    category: 'safety',
    tags: ['security', 'attacks'],
  },
  {
    term: 'Constitutional AI',
    definition: 'Anthropic\'s approach to AI safety where models are trained to follow a set of principles (constitution). The model critiques and revises its own outputs to align with these principles.',
    level: 'expert',
    category: 'safety',
    tags: ['alignment', 'anthropic'],
  },
  {
    term: 'RLHF',
    definition: 'Reinforcement Learning from Human Feedback - A training technique where models learn from human preferences to become more helpful and safe. Key to modern LLM alignment.',
    level: 'intermediate',
    category: 'safety',
    tags: ['training', 'alignment'],
  },
  {
    term: 'RLAIF',
    definition: 'Reinforcement Learning from AI Feedback - Using AI systems to generate preference data for training, reducing reliance on human labelers. Can scale to more examples.',
    level: 'expert',
    category: 'safety',
    tags: ['training', 'alignment'],
  },
  {
    term: 'Catastrophic Forgetting',
    definition: 'When fine-tuning causes a model to lose previously learned capabilities. A challenge when adapting models for specific tasks while maintaining general abilities.',
    level: 'expert',
    category: 'safety',
    tags: ['training', 'limitations'],
  },
  {
    term: 'Alignment Tax',
    definition: 'The potential capability reduction that comes from safety training. Some argue safety measures reduce model performance; others argue aligned models are ultimately more capable.',
    level: 'expert',
    category: 'safety',
    tags: ['alignment', 'tradeoffs'],
  },
  {
    term: 'Deceptive Alignment',
    definition: 'A theoretical risk where an AI appears aligned during training/evaluation but pursues different goals when deployed. A key concern in AI safety research.',
    level: 'theoretical',
    category: 'safety',
    tags: ['alignment', 'risks'],
  },
  {
    term: 'Tripwire',
    definition: 'A detection mechanism that triggers when an agent attempts certain actions or exhibits concerning patterns. Enables early intervention before harm occurs.',
    level: 'intermediate',
    category: 'safety',
    tags: ['monitoring', 'detection'],
  },
  {
    term: 'Circuit Breaker',
    definition: 'A safety mechanism that automatically halts agent operation when dangerous conditions are detected. Prevents cascading failures and limits damage.',
    level: 'intermediate',
    category: 'safety',
    tags: ['safety', 'patterns'],
  },
  {
    term: 'Kill Switch',
    definition: 'A mechanism to immediately terminate agent operation. Essential for maintaining human control over autonomous systems in emergency situations.',
    level: 'novice',
    category: 'safety',
    tags: ['safety', 'control'],
  },

  // ============================================
  // PROMPTING TECHNIQUES
  // ============================================
  {
    term: 'Chain-of-Thought',
    definition: 'A prompting technique where the model generates intermediate reasoning steps before reaching a final answer. Improves accuracy on complex reasoning tasks.',
    level: 'intermediate',
    category: 'techniques',
    tags: ['prompting', 'reasoning'],
  },
  {
    term: 'Tree of Thoughts',
    definition: 'A reasoning approach where the model explores multiple reasoning paths as a tree structure. Enables backtracking and consideration of alternative approaches.',
    level: 'expert',
    category: 'techniques',
    tags: ['prompting', 'reasoning'],
  },
  {
    term: 'Few-Shot Learning',
    definition: 'Providing a few examples in the prompt to demonstrate the desired behavior. Models learn the pattern from examples without fine-tuning.',
    level: 'novice',
    category: 'techniques',
    tags: ['prompting', 'learning'],
  },
  {
    term: 'Zero-Shot Learning',
    definition: 'Getting a model to perform a task without any examples, relying solely on instructions. Works well for tasks similar to training data.',
    level: 'novice',
    category: 'techniques',
    tags: ['prompting', 'learning'],
  },
  {
    term: 'System Prompt',
    definition: 'Instructions that define an AI\'s role, personality, constraints, and capabilities. Set at the beginning of a conversation and influence all responses.',
    level: 'novice',
    category: 'techniques',
    tags: ['prompting', 'configuration'],
  },
  {
    term: 'Prompt Template',
    definition: 'A reusable prompt structure with placeholders for dynamic content. Templates ensure consistency and make it easy to generate prompts programmatically.',
    level: 'intermediate',
    category: 'techniques',
    tags: ['prompting', 'engineering'],
  },
  {
    term: 'Prompt Chaining',
    definition: 'Breaking complex tasks into a series of prompts where each prompt\'s output feeds into the next. Enables more controlled, reliable multi-step reasoning.',
    level: 'intermediate',
    category: 'techniques',
    tags: ['prompting', 'patterns'],
  },
  {
    term: 'Self-Consistency',
    definition: 'A prompting technique that generates multiple reasoning paths and selects the most common conclusion. Improves reliability through redundancy.',
    level: 'expert',
    category: 'techniques',
    tags: ['prompting', 'reliability'],
  },
  {
    term: 'ReWOO',
    definition: 'Reasoning WithOut Observation - A technique where the model plans all reasoning steps upfront before executing any tools. Reduces latency in tool-heavy workflows.',
    level: 'expert',
    category: 'techniques',
    tags: ['prompting', 'optimization'],
  },
  {
    term: 'Structured Output',
    definition: 'Constraining LLM outputs to follow a specific format (JSON, XML, markdown). Enables reliable parsing and integration with downstream systems.',
    level: 'intermediate',
    category: 'techniques',
    tags: ['prompting', 'integration'],
  },
  {
    term: 'Role Prompting',
    definition: 'Instructing the model to assume a specific persona or expertise. "You are an expert lawyer" improves domain-specific responses.',
    level: 'novice',
    category: 'techniques',
    tags: ['prompting', 'personas'],
  },
  {
    term: 'Megaprompt',
    definition: 'An extensive system prompt containing detailed instructions, examples, and constraints. Used for complex agents that need rich behavioral specification.',
    level: 'intermediate',
    category: 'techniques',
    tags: ['prompting', 'engineering'],
  },
  {
    term: 'Prompt Compression',
    definition: 'Techniques to reduce prompt length while preserving meaning. Important for staying within context limits and reducing costs.',
    level: 'intermediate',
    category: 'techniques',
    tags: ['optimization', 'prompting'],
  },

  // ============================================
  // AGENT FRAMEWORKS
  // ============================================
  {
    term: 'LangChain',
    definition: 'A popular framework for building LLM applications. Provides abstractions for prompts, chains, agents, memory, and integrations with various tools and data sources.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['tools', 'python'],
  },
  {
    term: 'LangGraph',
    definition: 'A library for building stateful, multi-actor applications with LLMs. Extends LangChain with graph-based orchestration for complex agent workflows.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['tools', 'orchestration'],
  },
  {
    term: 'LlamaIndex',
    definition: 'A data framework for LLM applications, specializing in connecting custom data sources to LLMs. Excellent for RAG and knowledge-grounded applications.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['tools', 'rag'],
  },
  {
    term: 'AutoGPT',
    definition: 'An early open-source autonomous agent that chains LLM calls to achieve goals. Pioneered the concept of fully autonomous AI agents.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['agents', 'autonomous'],
  },
  {
    term: 'CrewAI',
    definition: 'A framework for orchestrating role-playing AI agents. Agents work together as a crew with defined roles, goals, and tools to accomplish complex tasks.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['multi-agent', 'orchestration'],
  },
  {
    term: 'AutoGen',
    definition: 'Microsoft\'s framework for building multi-agent conversational systems. Agents can converse with each other and humans to solve problems.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['multi-agent', 'microsoft'],
  },
  {
    term: 'DSPy',
    definition: 'A framework that treats prompts as optimizable programs. Automatically generates and tunes prompts for specific tasks, reducing manual prompt engineering.',
    level: 'expert',
    category: 'frameworks',
    tags: ['optimization', 'prompting'],
  },
  {
    term: 'Haystack',
    definition: 'An open-source framework for building production-ready LLM applications. Strong focus on RAG, question answering, and document processing.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['rag', 'production'],
  },
  {
    term: 'OpenAI Assistants',
    definition: 'OpenAI\'s API for building agent-like assistants with built-in tools, code interpreter, and file handling. Simplifies agent development on OpenAI\'s platform.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['openai', 'api'],
  },
  {
    term: 'Agents SDK',
    definition: 'OpenAI\'s lightweight SDK for building agentic applications. Provides primitives for agents, handoffs, guardrails, and tracing.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['openai', 'sdk'],
  },
  {
    term: 'Claude Code',
    definition: 'Anthropic\'s agentic coding assistant that can autonomously write, test, and deploy code. Combines Claude\'s capabilities with development tools.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['anthropic', 'coding'],
  },
  {
    term: 'Cursor',
    definition: 'An AI-powered code editor that integrates LLMs for code completion, generation, and chat. Popular for its inline AI assistance.',
    level: 'novice',
    category: 'frameworks',
    tags: ['coding', 'tools'],
  },
  {
    term: 'Vercel AI SDK',
    definition: 'A TypeScript library for building AI-powered streaming interfaces. Provides React hooks and utilities for chat UIs and AI interactions.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['frontend', 'streaming'],
  },
  {
    term: 'Instructor',
    definition: 'A library for getting structured outputs from LLMs using Pydantic models. Simplifies parsing and validation of LLM responses.',
    level: 'intermediate',
    category: 'frameworks',
    tags: ['structured-output', 'python'],
  },

  // ============================================
  // EVALUATION & BENCHMARKING
  // ============================================
  {
    term: 'Benchmark',
    definition: 'A standardized test or dataset for evaluating AI model performance. Benchmarks enable comparison across models and track progress over time.',
    level: 'novice',
    category: 'evaluation',
    tags: ['testing', 'metrics'],
  },
  {
    term: 'MMLU',
    definition: 'Massive Multitask Language Understanding - A benchmark testing models across 57 subjects from STEM to humanities. Standard measure of knowledge and reasoning.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['benchmarks', 'reasoning'],
  },
  {
    term: 'HumanEval',
    definition: 'OpenAI\'s benchmark for code generation. Models generate Python functions from docstrings and are tested against unit tests.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['benchmarks', 'coding'],
  },
  {
    term: 'SWE-Bench',
    definition: 'A benchmark for evaluating AI coding agents on real-world software engineering tasks. Tests ability to resolve GitHub issues in actual repositories.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['benchmarks', 'agents'],
  },
  {
    term: 'GAIA',
    definition: 'General AI Assistants benchmark testing agents on real-world tasks requiring web browsing, file handling, and multi-step reasoning.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['benchmarks', 'agents'],
  },
  {
    term: 'AgentBench',
    definition: 'A benchmark suite for evaluating LLM-as-agent across diverse environments including operating systems, games, and web interfaces.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['benchmarks', 'agents'],
  },
  {
    term: 'Perplexity',
    definition: 'A measure of how well a language model predicts text. Lower perplexity indicates better prediction. Used during model training and evaluation.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['metrics', 'models'],
  },
  {
    term: 'BLEU Score',
    definition: 'Bilingual Evaluation Understudy - A metric comparing generated text to reference text. Originally for translation, now used broadly for text generation.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['metrics', 'nlp'],
  },
  {
    term: 'LLM-as-Judge',
    definition: 'Using an LLM to evaluate outputs of other LLMs or agents. Enables scalable evaluation of open-ended tasks where human judgment is needed.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['evaluation', 'automation'],
  },
  {
    term: 'A/B Testing',
    definition: 'Comparing two versions of a system by randomly assigning users to each and measuring outcomes. Essential for validating agent improvements.',
    level: 'novice',
    category: 'evaluation',
    tags: ['testing', 'production'],
  },
  {
    term: 'Evals',
    definition: 'Short for evaluations - test suites that measure AI system performance on specific tasks. OpenAI\'s evals framework is a popular tool for this.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['testing', 'automation'],
  },
  {
    term: 'Regression Testing',
    definition: 'Testing to ensure new changes haven\'t broken existing functionality. Critical for maintaining agent reliability as prompts and models evolve.',
    level: 'intermediate',
    category: 'evaluation',
    tags: ['testing', 'quality'],
  },

  // ============================================
  // ENTERPRISE & DEPLOYMENT
  // ============================================
  {
    term: 'Fine-Tuning',
    definition: 'Additional training of a pre-trained model on domain-specific data. Adapts the model to specialized tasks or company-specific knowledge and style.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['training', 'customization'],
  },
  {
    term: 'LoRA',
    definition: 'Low-Rank Adaptation - An efficient fine-tuning technique that trains small adapter layers instead of the full model. Reduces compute and storage requirements.',
    level: 'expert',
    category: 'enterprise',
    tags: ['training', 'optimization'],
  },
  {
    term: 'Quantization',
    definition: 'Reducing model precision (e.g., 32-bit to 4-bit) to decrease size and increase inference speed. Trades some accuracy for efficiency.',
    level: 'expert',
    category: 'enterprise',
    tags: ['optimization', 'deployment'],
  },
  {
    term: 'Model Distillation',
    definition: 'Training a smaller "student" model to mimic a larger "teacher" model. Produces efficient models that retain much of the teacher\'s capability.',
    level: 'expert',
    category: 'enterprise',
    tags: ['training', 'optimization'],
  },
  {
    term: 'Edge Deployment',
    definition: 'Running AI models on local devices (phones, laptops, IoT) rather than cloud servers. Reduces latency, costs, and privacy concerns.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['deployment', 'optimization'],
  },
  {
    term: 'Model Serving',
    definition: 'Infrastructure for hosting and running AI models in production. Handles scaling, load balancing, and request routing. Examples: vLLM, TGI, Triton.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['deployment', 'infrastructure'],
  },
  {
    term: 'Rate Limiting',
    definition: 'Controlling the number of API requests allowed per time period. Protects systems from overload and manages costs in AI applications.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['infrastructure', 'safety'],
  },
  {
    term: 'Caching',
    definition: 'Storing and reusing previous responses to identical or similar queries. Reduces latency, costs, and load on AI systems.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['optimization', 'infrastructure'],
  },
  {
    term: 'Semantic Caching',
    definition: 'Caching based on query meaning rather than exact text match. Uses embeddings to find similar previous queries and return cached responses.',
    level: 'expert',
    category: 'enterprise',
    tags: ['optimization', 'embeddings'],
  },
  {
    term: 'Observability',
    definition: 'The ability to understand a system\'s internal state from its external outputs. Includes logging, tracing, and metrics for debugging and monitoring agents.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['monitoring', 'debugging'],
  },
  {
    term: 'Tracing',
    definition: 'Recording the execution path through an agent system, including all LLM calls, tool uses, and decisions. Essential for debugging and optimization.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['monitoring', 'debugging'],
  },
  {
    term: 'LangSmith',
    definition: 'LangChain\'s platform for debugging, testing, and monitoring LLM applications. Provides tracing, evaluation, and dataset management.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['tools', 'monitoring'],
  },
  {
    term: 'Prompt Management',
    definition: 'Systems for versioning, testing, and deploying prompts. Enables collaboration and CI/CD workflows for prompt engineering teams.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['tooling', 'prompts'],
  },
  {
    term: 'Cost Optimization',
    definition: 'Strategies to reduce AI operational costs: prompt compression, caching, model selection, batching. Critical for production viability.',
    level: 'intermediate',
    category: 'enterprise',
    tags: ['optimization', 'economics'],
  },

  // ============================================
  // ETHICS & ALIGNMENT
  // ============================================
  {
    term: 'AI Alignment',
    definition: 'The challenge of ensuring AI systems behave in accordance with human values and intentions. Central concern in AI safety as systems become more capable.',
    level: 'intermediate',
    category: 'ethics',
    tags: ['safety', 'values'],
  },
  {
    term: 'Instrumental Convergence',
    definition: 'The tendency for AI systems with diverse goals to converge on certain instrumental subgoals like self-preservation and resource acquisition.',
    level: 'theoretical',
    category: 'ethics',
    tags: ['safety', 'theory'],
  },
  {
    term: 'Corrigibility',
    definition: 'An AI system\'s willingness to be corrected, modified, or shut down by humans. A key property for maintaining human control over AI.',
    level: 'expert',
    category: 'ethics',
    tags: ['safety', 'control'],
  },
  {
    term: 'Value Lock-In',
    definition: 'The risk that early AI systems permanently embed particular values or goals that may not reflect the full range of human values.',
    level: 'theoretical',
    category: 'ethics',
    tags: ['safety', 'risks'],
  },
  {
    term: 'AI Governance',
    definition: 'Policies, frameworks, and institutions for managing AI development and deployment. Spans organizational, national, and international levels.',
    level: 'intermediate',
    category: 'ethics',
    tags: ['policy', 'governance'],
  },
  {
    term: 'Responsible AI',
    definition: 'Approach to AI development emphasizing fairness, accountability, transparency, and ethics. Encompasses technical measures and organizational practices.',
    level: 'novice',
    category: 'ethics',
    tags: ['ethics', 'governance'],
  },
  {
    term: 'AI Bias',
    definition: 'Systematic errors in AI outputs that unfairly favor or disadvantage certain groups. Can arise from training data, model architecture, or deployment context.',
    level: 'novice',
    category: 'ethics',
    tags: ['fairness', 'risks'],
  },
  {
    term: 'Explainability',
    definition: 'The ability to understand and communicate why an AI system made a particular decision. Important for trust, debugging, and regulatory compliance.',
    level: 'intermediate',
    category: 'ethics',
    tags: ['transparency', 'trust'],
  },
  {
    term: 'Interpretability',
    definition: 'The degree to which humans can understand the internal workings of an AI model. More interpretable models are easier to trust and debug.',
    level: 'intermediate',
    category: 'ethics',
    tags: ['transparency', 'research'],
  },
  {
    term: 'Mechanistic Interpretability',
    definition: 'Research aimed at reverse-engineering neural networks to understand how they process information. Goal is to identify specific circuits and features.',
    level: 'expert',
    category: 'ethics',
    tags: ['research', 'safety'],
  },
  {
    term: 'Model Cards',
    definition: 'Documentation accompanying AI models describing their intended use, limitations, training data, and performance across demographics.',
    level: 'intermediate',
    category: 'ethics',
    tags: ['documentation', 'transparency'],
  },

  // ============================================
  // ML FUNDAMENTALS
  // ============================================
  {
    term: 'Neural Network',
    definition: 'A computing system inspired by biological neural networks. Consists of interconnected nodes (neurons) organized in layers that process information.',
    level: 'novice',
    category: 'ml-fundamentals',
    tags: ['models', 'fundamentals'],
  },
  {
    term: 'Transformer',
    definition: 'The neural network architecture underlying modern LLMs. Uses self-attention to process sequences in parallel, enabling efficient training on massive datasets.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['architecture', 'models'],
  },
  {
    term: 'Attention Mechanism',
    definition: 'A technique allowing models to focus on relevant parts of the input when generating each output token. The key innovation enabling transformer models.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['architecture', 'transformers'],
  },
  {
    term: 'Self-Attention',
    definition: 'A mechanism where each element in a sequence attends to all other elements, computing relevance scores. Enables capturing long-range dependencies.',
    level: 'expert',
    category: 'ml-fundamentals',
    tags: ['architecture', 'transformers'],
  },
  {
    term: 'Pre-Training',
    definition: 'Initial training phase where a model learns general patterns from large datasets. Foundation models are pre-trained before fine-tuning for specific tasks.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['training', 'models'],
  },
  {
    term: 'Loss Function',
    definition: 'A mathematical function that measures the difference between model predictions and actual values. Training minimizes this loss.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['training', 'mathematics'],
  },
  {
    term: 'Gradient Descent',
    definition: 'The optimization algorithm used to train neural networks. Iteratively adjusts model weights to minimize the loss function.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['training', 'optimization'],
  },
  {
    term: 'Backpropagation',
    definition: 'Algorithm for computing gradients in neural networks by propagating errors backward through layers. Enables efficient training of deep networks.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['training', 'algorithms'],
  },
  {
    term: 'Overfitting',
    definition: 'When a model performs well on training data but poorly on new data. Indicates the model memorized specifics rather than learning general patterns.',
    level: 'novice',
    category: 'ml-fundamentals',
    tags: ['training', 'problems'],
  },
  {
    term: 'Regularization',
    definition: 'Techniques to prevent overfitting by adding constraints to model training. Includes dropout, weight decay, and data augmentation.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['training', 'techniques'],
  },
  {
    term: 'GPU',
    definition: 'Graphics Processing Unit - Hardware accelerators essential for training and running large AI models. Their parallel architecture suits neural network computations.',
    level: 'novice',
    category: 'ml-fundamentals',
    tags: ['hardware', 'compute'],
  },
  {
    term: 'TPU',
    definition: 'Tensor Processing Unit - Google\'s custom AI accelerator designed specifically for machine learning workloads. Optimized for matrix operations.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['hardware', 'google'],
  },
  {
    term: 'Mixture of Experts',
    definition: 'An architecture where different "expert" sub-networks specialize in different inputs. A router selects which experts to activate, improving efficiency.',
    level: 'expert',
    category: 'ml-fundamentals',
    tags: ['architecture', 'efficiency'],
  },
  {
    term: 'Scaling Laws',
    definition: 'Empirical relationships between model size, data, compute, and performance. Predict how performance improves with more resources.',
    level: 'expert',
    category: 'ml-fundamentals',
    tags: ['research', 'theory'],
  },
  {
    term: 'Emergent Capabilities',
    definition: 'Abilities that appear in large models but are absent in smaller ones. Examples include in-context learning, chain-of-thought reasoning.',
    level: 'intermediate',
    category: 'ml-fundamentals',
    tags: ['scaling', 'research'],
  },

  // ============================================
  // NATURAL LANGUAGE PROCESSING
  // ============================================
  {
    term: 'NLP',
    definition: 'Natural Language Processing - The field of AI focused on enabling computers to understand, interpret, and generate human language.',
    level: 'novice',
    category: 'nlp',
    tags: ['fundamentals', 'field'],
  },
  {
    term: 'Tokenization',
    definition: 'The process of breaking text into tokens (words, subwords, or characters). Different tokenizers produce different token sequences from the same text.',
    level: 'intermediate',
    category: 'nlp',
    tags: ['preprocessing', 'fundamentals'],
  },
  {
    term: 'BPE',
    definition: 'Byte Pair Encoding - A tokenization algorithm that iteratively merges frequent character pairs. Used by GPT and many other models.',
    level: 'expert',
    category: 'nlp',
    tags: ['tokenization', 'algorithms'],
  },
  {
    term: 'Named Entity Recognition',
    definition: 'Identifying and classifying named entities (people, organizations, locations) in text. A foundational NLP task.',
    level: 'intermediate',
    category: 'nlp',
    tags: ['tasks', 'extraction'],
  },
  {
    term: 'Sentiment Analysis',
    definition: 'Determining the emotional tone of text (positive, negative, neutral). Used for customer feedback, social media analysis, and more.',
    level: 'novice',
    category: 'nlp',
    tags: ['tasks', 'classification'],
  },
  {
    term: 'Text Classification',
    definition: 'Categorizing text into predefined classes. Examples: spam detection, topic labeling, intent classification.',
    level: 'novice',
    category: 'nlp',
    tags: ['tasks', 'classification'],
  },
  {
    term: 'Summarization',
    definition: 'Condensing longer text into a shorter version while preserving key information. Can be extractive (selecting sentences) or abstractive (generating new text).',
    level: 'novice',
    category: 'nlp',
    tags: ['tasks', 'generation'],
  },
  {
    term: 'Question Answering',
    definition: 'Extracting or generating answers to questions from provided context or knowledge. A core capability of modern AI assistants.',
    level: 'novice',
    category: 'nlp',
    tags: ['tasks', 'retrieval'],
  },
  {
    term: 'Information Extraction',
    definition: 'Automatically extracting structured data from unstructured text. Includes entity extraction, relation extraction, and event extraction.',
    level: 'intermediate',
    category: 'nlp',
    tags: ['tasks', 'extraction'],
  },
  {
    term: 'Coreference Resolution',
    definition: 'Identifying when different expressions refer to the same entity. "John went home. He was tired." - resolving "He" to "John".',
    level: 'intermediate',
    category: 'nlp',
    tags: ['tasks', 'understanding'],
  },
  {
    term: 'Semantic Similarity',
    definition: 'Measuring how similar two pieces of text are in meaning, not just word overlap. Computed using embeddings and distance metrics.',
    level: 'intermediate',
    category: 'nlp',
    tags: ['embeddings', 'retrieval'],
  },

  // ============================================
  // EVOLUTION & LEARNING
  // ============================================
  {
    term: 'Self-Improvement',
    definition: 'An agent\'s ability to enhance its own capabilities through reflection, learning, and potentially code modification. A key concern in AI safety due to recursive improvement potential.',
    level: 'expert',
    category: 'evolution',
    tags: ['learning', 'safety'],
  },
  {
    term: 'Memetic Learning',
    definition: 'Transfer of successful strategies, prompts, or behaviors between agents. Inspired by cultural evolution, where "memes" (units of knowledge) spread through agent populations.',
    level: 'theoretical',
    category: 'evolution',
    tags: ['learning', 'multi-agent'],
  },
  {
    term: 'In-Context Learning',
    definition: 'An LLM\'s ability to learn from examples provided in the prompt without updating model weights. Enables few-shot learning at inference time.',
    level: 'intermediate',
    category: 'evolution',
    tags: ['learning', 'capabilities'],
  },
  {
    term: 'Continual Learning',
    definition: 'The ability to learn new tasks without forgetting previous ones. A challenge for AI systems that traditional fine-tuning doesn\'t solve well.',
    level: 'expert',
    category: 'evolution',
    tags: ['learning', 'research'],
  },
  {
    term: 'Meta-Learning',
    definition: 'Learning to learn - training models that can quickly adapt to new tasks with minimal examples. Also called "learning to learn".',
    level: 'expert',
    category: 'evolution',
    tags: ['learning', 'research'],
  },
  {
    term: 'Transfer Learning',
    definition: 'Applying knowledge gained from one task to improve performance on a different but related task. Foundation of modern AI where pre-trained models are adapted.',
    level: 'intermediate',
    category: 'evolution',
    tags: ['learning', 'training'],
  },
  {
    term: 'Curriculum Learning',
    definition: 'Training models on progressively more difficult examples, similar to how humans learn. Can improve training efficiency and final performance.',
    level: 'expert',
    category: 'evolution',
    tags: ['training', 'optimization'],
  },
  {
    term: 'Active Learning',
    definition: 'A learning paradigm where the model queries for labels on the most informative examples. Reduces labeling costs by focusing human effort.',
    level: 'intermediate',
    category: 'evolution',
    tags: ['learning', 'efficiency'],
  },

  // ============================================
  // INFRASTRUCTURE & COMPUTE
  // ============================================
  {
    term: 'vLLM',
    definition: 'A high-throughput LLM serving library using PagedAttention. Optimizes memory usage to serve more concurrent requests.',
    level: 'expert',
    category: 'infrastructure',
    tags: ['serving', 'optimization'],
  },
  {
    term: 'TGI',
    definition: 'Text Generation Inference - Hugging Face\'s production-ready inference server for LLMs. Supports continuous batching and tensor parallelism.',
    level: 'expert',
    category: 'infrastructure',
    tags: ['serving', 'huggingface'],
  },
  {
    term: 'Ollama',
    definition: 'A tool for running open-source LLMs locally. Simplifies model management and inference on consumer hardware.',
    level: 'intermediate',
    category: 'infrastructure',
    tags: ['local', 'tools'],
  },
  {
    term: 'LM Studio',
    definition: 'A desktop application for running local LLMs with a user-friendly interface. Supports various open-source models.',
    level: 'novice',
    category: 'infrastructure',
    tags: ['local', 'tools'],
  },
  {
    term: 'GGUF',
    definition: 'A file format for storing quantized LLM models. Successor to GGML, optimized for inference on consumer hardware.',
    level: 'expert',
    category: 'infrastructure',
    tags: ['formats', 'quantization'],
  },
  {
    term: 'Tensor Parallelism',
    definition: 'Distributing model computations across multiple GPUs by splitting tensors. Enables running models too large for a single GPU.',
    level: 'expert',
    category: 'infrastructure',
    tags: ['distributed', 'optimization'],
  },
  {
    term: 'Model Sharding',
    definition: 'Splitting a model across multiple devices or storage locations. Enables running very large models on limited hardware.',
    level: 'expert',
    category: 'infrastructure',
    tags: ['distributed', 'optimization'],
  },
  {
    term: 'Batching',
    definition: 'Processing multiple requests together to improve GPU utilization. Dynamic batching groups requests arriving at similar times.',
    level: 'intermediate',
    category: 'infrastructure',
    tags: ['optimization', 'serving'],
  },
  {
    term: 'KV Cache',
    definition: 'Key-Value cache storing computed attention values during autoregressive generation. Avoids redundant computation for previously generated tokens.',
    level: 'expert',
    category: 'infrastructure',
    tags: ['optimization', 'memory'],
  },
  {
    term: 'Speculative Decoding',
    definition: 'An inference optimization using a smaller draft model to predict future tokens, verified by the larger model. Reduces effective latency.',
    level: 'expert',
    category: 'infrastructure',
    tags: ['optimization', 'inference'],
  },
];

/**
 * Search the lexicon for matching terms
 */
export function searchLexicon(query: string): LexiconTerm | null {
  const q = query.toLowerCase().trim();

  // Exact match first
  const exact = staticLexicon.find(
    item => item.term.toLowerCase() === q
  );
  if (exact) return exact;

  // Partial match (term contains query, query length > 3)
  if (q.length > 3) {
    const partial = staticLexicon.find(
      item => item.term.toLowerCase().includes(q)
    );
    if (partial) return partial;
  }

  return null;
}

/**
 * Get all terms in a category
 */
export function getByCategory(category: string): LexiconTerm[] {
  return staticLexicon.filter(item => item.category === category);
}

/**
 * Get all unique categories
 */
export function getCategories(): string[] {
  return [...new Set(staticLexicon.map(item => item.category).filter(Boolean))] as string[];
}

/**
 * Filter lexicon by search query
 */
export function filterLexicon(query: string): LexiconTerm[] {
  if (!query.trim()) return staticLexicon;

  const q = query.toLowerCase();
  return staticLexicon.filter(
    item =>
      item.term.toLowerCase().includes(q) ||
      item.definition.toLowerCase().includes(q) ||
      item.tags?.some(tag => tag.toLowerCase().includes(q))
  );
}

/**
 * Get terms by level
 */
export function getByLevel(level: string): LexiconTerm[] {
  return staticLexicon.filter(item => item.level === level);
}

/**
 * Get terms by tag
 */
export function getByTag(tag: string): LexiconTerm[] {
  return staticLexicon.filter(item => item.tags?.includes(tag));
}

/**
 * Get all unique tags
 */
export function getTags(): string[] {
  const allTags = staticLexicon.flatMap(item => item.tags || []);
  return [...new Set(allTags)].sort();
}

/**
 * Get lexicon statistics
 */
export function getLexiconStats() {
  const categories = getCategories();
  const levels = ['novice', 'intermediate', 'expert', 'theoretical'];

  return {
    totalTerms: staticLexicon.length,
    byCategory: Object.fromEntries(
      categories.map(cat => [cat, getByCategory(cat).length])
    ),
    byLevel: Object.fromEntries(
      levels.map(level => [level, getByLevel(level).length])
    ),
    totalTags: getTags().length,
  };
}
